import theme from "@/styles/theme";
import styled from "styled-components";
import Navigation from "./Navigation";
import Head from "next/head";
import Image from "next/image";
import BackgroundImage from "@/assets/images/background.svg";

const LayoutContainer = styled.div`
  position: relative;
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  width: 100vw;
`;

const LayoutContent = styled.div`
  position: relative;
  width: 100%;
  min-height: 100vh;
  padding: 20px;
`;

const LayoutBackground = styled.div`
  position: absolute;
  top: 0;
  left: 0;
`;

const LayoutBackgroundImage = styled.div`
  position: relative;
  width: 100vw;
`;

const LayoutNavigation = styled.div`
  height: 100px !important;
`;

const Layout = ({ children }: { children: any }) => {
  return (
    <>
      <Head>
        <title>Autopass3 - Merchant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <LayoutBackground>
        <LayoutBackgroundImage>
          <Image src={BackgroundImage} alt="Background" />
        </LayoutBackgroundImage>
      </LayoutBackground> */}

      <LayoutNavigation>
        <Navigation />
      </LayoutNavigation>

      <LayoutContainer>
        <LayoutContent>{children}</LayoutContent>
      </LayoutContainer>
    </>
  );
};

export default Layout;
